# app.py
import dash
from layout import create_layout

# --- Initialize the App ---
# We pass __name__ so Dash knows where to find assets and other files.
app = dash.Dash(
    __name__, 
    external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'],
    suppress_callback_exceptions=True
)

app.title = "Data Center Sustainability Co-Pilot"
server = app.server # Expose the server variable for deployments

# --- Set the Layout ---
# The layout is now generated by our function from layout.py
app.layout = create_layout()

# --- Import Callbacks ---
# This is a crucial step. By importing the callbacks module here,
# we ensure that the callbacks are registered with the app.
import callbacks